new: ユーザーprefixを作った。
RextTeam/rt-bot pull request #133
Opened 2022-06-14 00:41 UTC by yaakiyu

新規機能追加です。
ユーザーprefixの設定ができるようにしました

2022-06-14 01:40 UTC, tuna2134 commented
> 新規機能追加です。
> ユーザーprefixの設定ができるようにしました

できればissueを中心に作ってくれないかな？

2022-06-14 01:42 UTC, tuna2134 commented
こればかりは僕だけでは決めれない

2022-06-14 01:42 UTC, tuna2134 commented
@tasuren これどうかな？

2022-06-14 01:43 UTC, tuna2134 commented
僕は賛成だけど

2022-06-14 01:51 UTC, yaakiyu commented
freeRTでできるようにしようとしたことだったからね
freeRT系の新機能のうち最も作りやすかった

2022-06-14 01:57 UTC, tuna2134 commented
> freeRTでできるようにしようとしたことだったからね
> freeRT系の新機能のうち最も作りやすかった

なるほどね

2022-06-14 01:58 UTC, tuna2134 commented
これはtasurenかな

2022-06-14 04:23 UTC, tasuren requested changes
Wave 1

2022-06-14 04:23 UTC, tasuren commented on cogs/rt/prefix.py
> +        for row in await cursor.fetchall():
`cursor.fetchall`を`self.fetchstep`にして欲しい。

2022-06-14 04:23 UTC, tasuren commented on cogs/rt/prefix.py
> +    async def set_user(self, user_id: int, prefix: Optional[str] = None):
`set_guild`と統合して欲しい。引数に`mode: Literal["guild", "user"]`ってやってさ。

2022-06-14 04:23 UTC, tasuren commented on cogs/rt/prefix.py
> +    async def prefix(self, ctx: commands.Context,
これ、引数のとこから改行して欲しい。

2022-06-14 04:23 UTC, tasuren commented on cogs/rt/prefix.py
> +                    ja=f"{se_ja}未設定にしました。",
`se_ja`がない。

2022-06-14 04:23 UTC, tasuren commented on cogs/rt/prefix.py
> +                    en=f"Unset custom prefixes {}."
`{}`の中身がない。

2022-06-14 04:38 UTC, yaakiyu commented
修正した。

2022-06-14 04:40 UTC, tuna2134 commented
まだあると思うからある程度身構えよう(tasuren)

2022-06-14 05:11 UTC, tasuren requested changes
Wave 2

2022-06-14 05:11 UTC, tasuren commented on cogs/rt/prefix.py
> +        async for rows in self.fetchstep(cursor, "SELECT * FROM GuildPrefix;"):
テーブル名がユーザーの方になっていない。

2022-06-14 05:11 UTC, tasuren commented on cogs/rt/prefix.py
> +        await cursor.execute(
`fetchstep`を使うのならこれはもういらない。

2022-06-14 05:11 UTC, tasuren commented on cogs/rt/prefix.py
> +    async def set(self, mode: Literal["server", "user"], id_: int, prefix: Optional[str] = None):
統合はもっと統合して欲しい。
SQL文内のテーブル名を動的に変えるようにしてほしい。
`table = "Guild" if mode == "server" else "User"`みたいにして。
でも、それするのなら`TableType: TypeAlias = Literal["Guild", "User"]にして、この関数の`mode: Literal[...]`引数を`table: TableType`にした方が良いね。
そして、`self.user_prefixes[id_]`を`self.prefixes["User"][id_]`みたいにアクセスできるようにすると良さそう。

2022-06-14 05:11 UTC, tasuren commented on cogs/rt/prefix.py
> +        self, ctx: commands.Context, mode: Literal["user", "server"], *, prefix: Optional[str] = None
一行だと見た目があまり良い気分になるものでないから、`*,`あたりで改行してほしい。

2022-06-14 05:11 UTC, tasuren commented on cogs/rt/prefix.py
> +        mo_ja = f"{'このサーバー' if mode != "user" else 'あなた'}のカスタムプリフィックスを"
これ(`mo`シリーズ)を辞書にまとめて定数に入れて、その定数の定義をこの関数のすぐ上に配置してほしい。

2022-06-14 05:14 UTC, tuna2134 commented
ほらきた()

2022-06-14 06:43 UTC, yaakiyu commented on cogs/rt/prefix.py
> +        await cursor.execute(
これ本当にいらない?
ユーザーprefixテーブルの作成だけど

2022-06-14 07:12 UTC, tasuren commented on cogs/rt/prefix.py
> +        await cursor.execute(
あ、ほんとだ。
じゃあ大丈夫

2022-06-14 07:20 UTC, tasuren requested changes
Wave 3

2022-06-14 07:20 UTC, tasuren commented on core/types_.py
> +class Prefixes(TypedDict):
これ一つのファイルでしか使わないから、そこで定義してほしい。

2022-06-14 07:20 UTC, tasuren commented on cogs/rt/prefix.py
> +        await self.data.set(
これの上に空の行を入れてほしい。

2022-06-14 07:20 UTC, tasuren commented on cogs/rt/prefix.py
> +        for guild_id in self.bot.prefixes["Guild"]:
ここ処理テーブル名以外コードが同じだから、テーブル名を`for`で回して同じコードを一つにしてほしい。

2022-06-14 07:20 UTC, tasuren commented on cogs/rt/prefix.py
> +    async def set(self, mode: TableType, id_: int, prefix: Optional[str] = None):
`mode`のひきすう名を`table`にして欲しい。
コマンドの方の引数と混合する。

2022-06-14 07:20 UTC, tasuren commented on cogs/rt/prefix.py
> +        async for rows in self.fetchstep(cursor, "SELECT * FROM UserPrefix;"):
`"Guild"`の方のコードを使えるようにテーブル名を`for`で回して欲しい。

2022-06-14 08:26 UTC, tasuren commented on cogs/rt/prefix.py
> +        for table in ["Guild", "User"]:
可変じゃないのならリストではなくタプルにして欲しい。

2022-06-14 08:29 UTC, tasuren commented on core/bot.py
> +class Prefixes(TypedDict):
このクラスの間にからの行をもう一つ入れてくれ。

2022-06-14 08:30 UTC, tasuren commented on cogs/rt/prefix.py
> +        for table in ["Guild", "User"]:
https://github.com/RextTeam/rt-bot/pull/133#discussion_r896527082
と同じ。

2022-06-14 08:31 UTC, tasuren commented
> > 新規機能追加です。
> > ユーザーprefixの設定ができるようにしました
> 
> できればissueを中心に作ってくれないかな？
> 

それがいいね。
作る内容を事前に知らせておく。
却下されたとしたらPRだす労力が無駄になってしまう。

2022-06-14 08:55 UTC, tasuren requested changes
Wave 5
Fight

2022-06-14 08:55 UTC, tasuren commented on cogs/rt/prefix.py
> +                        f"DELETE FROM {table}Prefix WHERE {table}Id = %s;", (id_,)
少し長い一行だけってなんか気持ち悪い。
第二引数を次の行にして欲しい。

2022-06-14 08:55 UTC, tasuren commented on cogs/rt/prefix.py
> +                    f"DELETE FROM {table}Prefix WHERE GuildId = %s;", (id_,)
https://github.com/RextTeam/rt-bot/pull/133#discussion_r896556518
と同じ

2022-06-14 10:23 UTC, tasuren requested changes
Wave 6

2022-06-14 10:23 UTC, tasuren commented on cogs/rt/prefix.py
> +                if not await self.bot.exists(table.lower(), id_):
毎回lowerしないようにmapで一回だけlowerするようにして欲しい。

2022-06-14 23:26 UTC, yaakiyu commented on cogs/rt/prefix.py
> +                if not await self.bot.exists(table.lower(), id_):
mapで`.〇〇()`ってどうやってやるんだろう
とりあえず2回だけlowerするようにしたけども

2022-06-14 23:56 UTC, tasuren requested changes
Wave 7

2022-06-14 23:56 UTC, tasuren commented on cogs/rt/prefix.py
> +            lower = table.lower()
変数名を`lowered`にしてほしい。
過去分詞

2022-06-15 01:13 UTC, tasuren approved these changes
Nice job

2022-06-15 01:13 UTC, merged