update: blocker作成途中
RextTeam/rt-bot pull request #136
Opened 2022-06-14 03:13 UTC by yaakiyu

# Pull Request

## チェックリスト

- [x] 新規機能追加

まだ作業途中です。

2022-06-14 04:38 UTC, tuna2134 commented
Draftにしといた

2022-06-14 04:38 UTC, yaakiyu commented
ok

2022-06-15 13:29 UTC, yaakiyu commented
終わった。

2022-06-15 22:29 UTC, tasuren requested changes
Wave is coming!

2022-06-15 22:29 UTC, tasuren commented on cogs/server-management2/blocker.py
> +    MODES_CL: TypeAlias = Literal["Emoji", "Stamp", "Reaction"]
`TABLES`にして欲しい。
`CL`と`L`だと曖昧でよく分からない。
いや、これ型だから`Tables`にして。

2022-06-15 22:29 UTC, tasuren commented on cogs/server-management2/blocker.py
> +    MODES_L: TypeAlias = Literal["emoji", "stamp", "reaction", "all"]
これ型だから名前を`Mode`にして。

2022-06-15 22:29 UTC, tasuren commented on cogs/server-management2/blocker.py
> +    @commands.guild_only()
新RTはDM受け付けないからこれはやらないでOK。

2022-06-15 22:29 UTC, tasuren commented on cogs/server-management2/blocker.py
> +
恐らく`DtaaManager`のコンストラクタの`cog`引数の型が見つからないってエラーが出るから、`from __future__ import annotations`をここに入れて。

2022-06-15 22:29 UTC, tasuren commented on cogs/server-management2/blocker.py
> +from rtlib.common.json import loads, dumps
coreの下がいい。

2022-06-15 23:57 UTC, yaakiyu commented
修正。@tasuren

2022-06-15 23:58 UTC, yaakiyu commented
(このPRで人生初のTypeAliasを使った。)
(というか一回機能作ると慣れるもんだな。なんとなくRTの仕組みわかってきた。)

2022-06-16 01:37 UTC, tuna2134 commented
なんか楽そうで羨ましい()

2022-06-17 00:26 UTC, yaakiyu commented
@tasuren もう修正終わってるよー

2022-06-17 07:24 UTC, tasuren requested changes
The wave is coming.

2022-06-17 07:24 UTC, tasuren commented on cogs/server-management2/blocker.py
> +                )  # 見つからなくても正常に実行されるらしい
このコメントいらない。

2022-06-17 07:56 UTC, yaakiyu commented on cogs/server-management2/blocker.py
> +                    GuildId BIGINT PRIMARY KEY NOT NULL, Blocking BOOLEAN,
それぞれのモードにおいて別々にロール指定とか例外指定とかできるようにしたいから。

2022-06-17 09:38 UTC, tasuren commented on cogs/server-management2/blocker.py
> +                    GuildId BIGINT PRIMARY KEY NOT NULL, Blocking BOOLEAN,
`Mode`っていうコラム作るじゃダメなの？

2022-06-19 01:48 UTC, yaakiyu commented on cogs/server-management2/blocker.py
> +            return
それたぶんallの時に下の処理を実行させないようにするためのreturnなのでいると思う。

2022-06-19 03:02 UTC, tasuren commented on cogs/server-management2/blocker.py
> +            return
あ、下みてなかった。
Okay

2022-06-23 04:17 UTC, yaakiyu commented on cogs/server-management2/blocker.py
> +                )  # 見つからなくても正常に実行されるらしい
コーシング中に適当に書いたやつ残ってた()

2022-06-23 05:18 UTC, yaakiyu commented
修正。
@tasuren

2022-06-24 23:09 UTC, tasuren requested changes
The wave is coming!

2022-06-24 23:09 UTC, tasuren commented on cogs/server-management2/blocker.py
> +    MODES: tuple[Modes, Modes, Modes, Modes]
これいらない。

2022-06-24 23:09 UTC, tasuren commented on cogs/server-management2/blocker.py
> +        for mo in self.data.MODES:
`mo`とか短縮するのやめて。

2022-06-24 23:09 UTC, tasuren commented on cogs/server-management2/blocker.py
> +            se = await self.data.get_settings(ctx.guild.id, mo, "Blocking, Roles")
`se`とか省略するのやめて。

2022-06-24 23:09 UTC, tasuren commented on cogs/server-management2/blocker.py
> +    async def add(self, ctx, mode: DataManager.Modes, role: discord.Role):
`role`の左に`*`を置いて。

2022-06-24 23:09 UTC, tasuren commented on cogs/server-management2/blocker.py
> +    async def remove(self, ctx, mode: DataManager.Modes, role: discord.Role):
`role`の左に`*`を置いて。

2022-06-24 23:09 UTC, tasuren commented on cogs/server-management2/blocker.py
> +            or message.guild.id not in self.data.onoff_cache
インデントを一つ置いて。

2022-06-24 23:09 UTC, tasuren commented on cogs/server-management2/blocker.py
> +                try:
`try`の部分を関数にして実装して。

2022-06-24 23:09 UTC, tasuren commented on cogs/server-management2/blocker.py
> +        if c := message.stickers:
`if`の度に前に空の行を入れて。

2022-06-24 23:09 UTC, tasuren commented on cogs/server-management2/blocker.py
> +                ))
この一つ目の括弧閉じを作った括弧がインデントされてるなら、この括弧閉じもインデントされるべき。

2022-06-24 23:09 UTC, tasuren commented on cogs/server-management2/blocker.py
> +            or reaction.message.guild.id not in self.data.onoff_cache
ここインデント入れて。

2022-06-24 23:09 UTC, tasuren commented on cogs/server-management2/blocker.py
> +        self.cache: Cacher = self.cog.bot.cachers.acquire(30.0)  # 荒らし防止用キャッシュ
`anti_spam_caches`に名前を変えて。

2022-06-24 23:09 UTC, tasuren commented on cogs/server-management2/blocker.py
> +        self.onoff_cache = defaultdict(dict)
`caches`にして。

2022-06-25 07:22 UTC, yaakiyu commented on cogs/server-management2/blocker.py
> +    MODES: tuple[Modes, Modes, Modes, Modes]
これやっとかないとpyrightがエラー吐くもんで

2022-06-25 07:38 UTC, tasuren commented on cogs/server-management2/blocker.py
> +    MODES: tuple[Modes, Modes, Modes, Modes]
basicモードにしてる？

2022-06-25 10:10 UTC, yaakiyu commented on cogs/server-management2/blocker.py
> +    MODES: tuple[Modes, Modes, Modes, Modes]
わかんないけど
確かMODESをforで回して関数を呼び出したときにstrとLiteralが合ってないぞって言われて
pyrightのMODESの推論が`tuple[str, str, str, str]`になってたっぽいんだよね

2022-06-25 21:53 UTC, tasuren commented on cogs/server-management2/blocker.py
> +    MODES: tuple[Modes, Modes, Modes, Modes]
どこでそうなった？

2022-06-25 23:07 UTC, yaakiyu commented on cogs/server-management2/blocker.py
> +    MODES: tuple[Modes, Modes, Modes, Modes]
190行目とか

2022-06-25 23:14 UTC, tasuren commented on cogs/server-management2/blocker.py
> +    MODES: tuple[Modes, Modes, Modes, Modes]
じゃあ`MODES: tuple[Mode, ...] = (...)`って感じにして。

2022-06-26 23:41 UTC, yaakiyu commented
修正。
@tasuren

2022-06-27 01:30 UTC, tasuren requested changes
レビューするの結構長くなりそうだから後はぼくがやりたい。

2022-06-27 02:44 UTC, yaakiyu commented on cogs/server-management2/blocker.py
> +    async def try_delete(self, message: discord.Message, mode: str):
しようと思ったけど
それぞれのイベントでとる引数が違うんだよな
どう実装しよう

2022-06-27 03:37 UTC, tasuren commented on cogs/server-management2/blocker.py
> +    async def try_delete(self, message: discord.Message, mode: str):
`**kwargs`みたいにやっちゃダメなん？

2022-06-27 04:31 UTC, yaakiyu commented on cogs/server-management2/blocker.py
> +    async def try_delete(self, message: discord.Message, mode: str):
確かに。()()

2022-06-28 02:21 UTC, yaakiyu commented on cogs/server-management2/blocker.py
> +    async def add(self, ctx, mode: DataManager.Modes, *, role: discord.Role):
guild.rolesにeveryoneがあるから多分設定できる。

2022-06-28 03:44 UTC, yaakiyu commented
修正。
@tasuren

2022-06-28 04:19 UTC, tasuren commented on cogs/server-management2/blocker.py
> +    async def add(self, ctx, mode: DataManager.Modes, *, role: discord.Role):
それってメンションじゃなくてもいけるの？

2022-06-28 04:20 UTC, tasuren commented
> レビューするの結構長くなりそうだから後はぼくがやりたい。

↑見た？

2022-06-28 04:45 UTC, yaakiyu commented
あ
みてなかった
ごめん

2022-06-28 07:17 UTC, tasuren commented
じゃあブランチ変えよう。

2022-06-29 05:01 UTC, tasuren approved these changes
後は僕がやる。

2022-06-29 05:01 UTC, merged