add: globalchat(途中やり)
RextTeam/rt-bot pull request #138
Opened 2022-06-14 04:59 UTC by tuna2134

# Pull Request

## チェックリスト

- [ ] 新規機能追加

2022-06-14 14:05 UTC, tuna2134 commented
ふうつかれた

2022-06-14 20:22 UTC, tasuren requested changes
Wave 1

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +from core import (
一行にまとめて。

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +from discord import utils, app_commands
`discord`があるからそっからこれら使って。

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +# RT - server-tool global
前も言ったよね。
コメントアウトの次に空の行を入れて。

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +from typing import AsyncIterator, Optional
`typing.AsyncIterator`は3.9から`collections.abc.AsyncIterator`で使えるようになった。
と同時に`typing.AsyncIterator`は非推奨になった。
`collections.abc.AsyncIterator`のimportをこの行のすぐ下に作って。
あと、`Optional`は`| None`にして欲しい。

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    """
見ればわかるからこんなにコメントいらない。
一行で良い。
(他の関数もそう。)

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            "SELECT * FROM GlobalChat WHERE name=%s",
イコールの周りにスペース入れて欲しい。

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def prepare_table(self) -> None:
`"テーブルを作ります。"`とかコメント入れておいて。

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                name TEXT, channelid BIGINT);"""
ここの最後の括弧改行して。
それと、コラム名はキャメルケースにして。
e.g. `Name`, `ChannelId`

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    WEBHOOK_NAME: str = "rt-globalchat-webhook"
この行の上にコグのコメント(`"グローバルチャットのコグです。"`)と空の行を入れてほしい。
あと、この定数に付いている型付けは、推論してくれるからなくても良い。

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        if ctx.invoked_subcommand is None:
`await self.group_index(ctx)`を使って欲しい。

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        aliases=("gc", "gchat")
`fsparent`の指定をして欲しい。

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        aliases=("make", "add")
`data`に`CREATE_ALIASES`とかなかったっけ。

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                dict(
改行しないで詰めてって規約に書いてなかったっけ？

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        if (await self.data.check_exist(ctx.channel)):
この括弧いらない。

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        name = "default" if name is None else name
この変数一度しか使わないから変数作る必要がない。

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        aliases=("join",)
日本語のエイリアスも作ってほしい。
通常の英語の別名と英語の一文字か二文字くらいと日本語と日本語の一文字か二文字のひらがなって感じに入れてほしい。

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                 )
これインデントされすぎ。

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    Cog.HelpCommand(globalchat) \
これ`\`だとめんどくさいから括弧で囲んでやって。

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                          ja="グローバルチャット名",
インデントを括弧のとこに合わせないで。

2022-06-14 20:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +async def setup(bot: RT):
返り値を入れておいて。

2022-06-14 22:51 UTC, yaakiyu commented
修正大変そうだね()

2022-06-14 22:52 UTC, tuna2134 commented
そっか？
全然まだ楽なんだけど

2022-06-14 22:53 UTC, ysmreg commented
私もこれは大変だと思うけど

2022-06-14 22:55 UTC, tuna2134 commented on cogs/server-tool/globalchat.py
> +    """
えー
一応もしものためにあるんだけど()

2022-06-14 22:56 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    """
いらない。

2022-06-14 23:00 UTC, tuna2134 commented
全然
これよりもっとあった時もあったし

2022-06-14 23:20 UTC, yaakiyu commented
逆にもっとあった時はどんだけ酷かったんだ((

2022-06-14 23:20 UTC, tuna2134 commented on cogs/server-tool/globalchat.py
> +                dict(
> 逆にもっとあった時はどんだけ酷かったんだ((

今よりコード規約とか整備されてなかった

2022-06-14 23:21 UTC, tuna2134 commented
> 逆にもっとあった時はどんだけ酷かったんだ((

今よりコード規約とか整備されてなかった

2022-06-14 23:23 UTC, tasuren requested changes
Wave 2

2022-06-14 23:23 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    WEBHOOK_NAME: str = "rt-globalchat-webhook"
> あと、この定数に付いている型付けは、推論してくれるからなくても良い。

がなおっていない。

2022-06-14 23:23 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        if (await self.data.check_exist(ctx.channel)):
治っていない。

2022-06-14 23:23 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                dict(en="You connected another one.", ja="もうすでにあなたは接続をしています。"),
```python
await ctx.reply(t(dict(
  ...
), ctx))
```
みたいな感じにしてほしい。

2022-06-14 23:24 UTC, tuna2134 commented on cogs/server-tool/globalchat.py
> +                dict(en="You connected another one.", ja="もうすでにあなたは接続をしています。"),
i see

2022-06-14 23:28 UTC, tuna2134 commented
修正した

2022-06-14 23:52 UTC, tasuren requested changes
Wave 3

**WARNING: LittleBreakingChange**
データベースのテーブルの構成の変更を要求する。
詳細はレビューコメントにて。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        if (await cursor.fetchone()) is not None:
念の為`not await cursro.fetchone()`にして欲しい。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            "SELECT * FROM GlobalChat WHERE name = %s",
SQLは最後に`;`を付けて欲しい。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def prepare_table(self) -> None:
これが治っていない。
あとこの関数`__init__`の下がいい。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                name TEXT, channelid BIGINT
SQLのコラム名はキャメルケースにしてほしい。
あと、テーブルの構成作り直そう。
```sql
Name TEXT, ChannelId BIGINT PRIMARY KEY NOT NULL, Setting JSON
```
にしよう。
`PRIMARY KEY`わからないのなら検索して。あと`ON DUPLICATE KEY UPDATE`も調べて。
`Setting`は設定を格納したJSONで、これに格納する設定は公開設定とかパスワードとかクールダウンとかね。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def check_exist(self, channel: discord.TextChannel) -> bool:
`is_connected`って名前にしてほしい。
あと、引数をオブジェクトにする必要性がないから、`channel_id: int`にしてほしい。
他も同じような箇所があればそこもそうして。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        return (await cursor.fetchone()) is not None
`bool(await cursor.fetchone())`にしてほしい。
他も同じような箇所があればそこもそうして。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def check_exist_gc(self, name: str) -> bool:
`check_exists`に名前を変えてほしい。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                await self.disconnect(channel)
引数に`cursor=cursor`ってやって同じ`cursor`使うようにしてほしい。
これをするとLintは同然`cursor`引数はないってエラー出すから、`disconnect`関数に`**_`って入れて。
他も別の関数実行する時は`cursor`引数を使い回しできるようにしてほしい。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    ) -> Optional[discord.TextChannel]:
`| None`って感じにしてほしい。
他もそう。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            None, partial(self.bot.get_channel, channelid)
こんくらいならもう`lambda`使ってほしい。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        else:
この`else`いらない。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                return await self.bot.fetch_channel(channelid)
チャンネルはちゃんと取得できることが保証されているから、これは`get_channel`で良い。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        data = await cursor.fetchone()
```python
if row := await cursor.fetchone():
  return row[0]
```
って感じにしてほしい。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        await cursor.execute(
コメントをつけてほしい。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        aliases=("gc", "gchat"),
これ改行しなくて良い。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        description="Setup global chat",
説明を`The command of globalchat.`にして欲しい。
これはグローバルチャット全体のコマンドだから、設定するだけのコマンドではない。

2022-06-14 23:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                source BIGINT, channelid BIGINT, messageid BIGINT
これチャンネルIDとかじゃなくてグローバルチャットの名前と送信者IDとメッセージIDにして。

2022-06-14 23:54 UTC, tuna2134 commented on cogs/server-tool/globalchat.py
> +                name TEXT, channelid BIGINT
わかった

2022-06-14 23:58 UTC, tuna2134 commented on cogs/server-tool/globalchat.py
> +                source BIGINT, channelid BIGINT, messageid BIGINT
Ok

2022-06-15 00:00 UTC, tuna2134 commented on cogs/server-tool/globalchat.py
> +                await self.disconnect(channel)
どういうこと？

2022-06-15 00:02 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                await self.disconnect(channel)
この状態だと新しいCursorが作られてしまう。
だから`cursor`を渡してほしい。
```python
await self.disconnect(channel, cursor=cursor)
```
って感じにすればいい。
`async def disconnect(channel: ..., **_) -> ...: ...`っていう定義にすればLinterはエラーを出さないからそうして。

2022-06-15 00:30 UTC, tuna2134 commented
修正多分終わった

2022-06-15 00:31 UTC, tasuren requested changes
Wave is coming!

2022-06-15 00:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def connect(self, name: str, channelid: int) -> None:
` channelid`を`channel_id`にしてほしい。

2022-06-15 00:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
>              );"""
コラム名をキャメルケースにしてほしい。

2022-06-15 00:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            channel = await loop.run_in_executor(None, self.bot.get_channel, partial(channelid))
なんで`run_in_executor`でやっているの？

2022-06-15 00:37 UTC, tuna2134 commented
> Wave is coming!

こまかいのう

2022-06-15 00:43 UTC, tasuren requested changes
LittleWave is coming.

2022-06-15 00:43 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                Source BIGINT, ChannelId BIGINT, MessageId BIGINT
グローバルチャット名も入れておけば？

2022-06-15 00:43 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                Name TEXT, ChannelId BIGINT PRIMARY KEY NOT NULL, Setting JSON
まった、やっぱやめた。
`ChannelId PRIMARY KEY NOT NULL`を消して、`Channels JSON`ってやって。
そこにチャンネルIDのリストを入れる。

2022-06-15 02:14 UTC, tasuren requested changes
Wave is coming!

2022-06-15 02:14 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def prepare_table(self) -> None:
これなおっていない。

2022-06-15 02:14 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                Source BIGINT, ChannelId BIGINT, MessageId BIGINT
Hey

2022-06-15 02:14 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            "SELECT * FROM GlobalChatChannel WHERE ChannelId = %s;",
`*`を`Name`にして名前しか取得しないようにして。
あと`LIMIT 1`を最後に付けて一つ取得したらすぐ検索終了するようにして。
他も一つしか取得しなくていい場合はそうして。

2022-06-15 02:14 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            "DELETE FROM GlobalChatChannel WHERE ChannelId = %s;", (channel_id,)
長い一行だけは気持ち悪いから第二引数を改行してほしい。

2022-06-15 02:14 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            "default" if name is None else name, ctx.author.id, ctx.channel.id, {"password": password}
デフォルトやめて。
被りかねないじゃん？
それと、Settingの型を`typing.TypedDict`を使って作って。
あとresult変数一度しか使わないなら作る必要ない。
ifにこの`create_chat`直接ぶち込んで。
それと全体に言えることなんだけど`async with ctx.typing():`置いて。
もしデータベース取得した値をそのまま返信するのなら`await ctx.typing()`をやって。

2022-06-15 02:14 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        self, name: str, author_id: int, channel_id: int, settings: Dict[str, Any]
そのdictの型付けのやり方は3.9から非推奨だから`dict[str, Any]`にして。

2022-06-15 02:14 UTC, tasuren commented on cogs/server-tool/globalchat.py
>      async def insert_message(
この行に対して言ってるんじゃないけど、123行目の空の行を消して、`globalchat`コマンドグループのデコレータの引数の`aliases`改行しないようにして。

2022-06-15 12:56 UTC, tasuren requested changes
Wave is coming!

2022-06-15 12:56 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def connect(self, name: str, channelid: int) -> None:
これがなおっていない。

2022-06-15 12:56 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        self, name: str, author_id: int, channel_id: int, settings: dict[str, Any]
`settings`の型を`TypedDict`で作って。

2022-06-15 12:56 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +from orjson import dumps
`loads`と`dumps`は`from rtlib.common.json import loads, dumps`でimportして。

2022-06-15 12:56 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    "グローバルチャットのデータベースを管理します。"
データベースというよりテーブルだから、文が厳密にはあっていない。
「セーブデータを管理します」にして。

2022-06-15 12:56 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        self, name: str
ここ改行する必要がない。

2022-06-15 12:56 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                          ja="グローバルチャット名",
ここがなおっていない。

2022-06-15 21:47 UTC, tasuren requested changes
Wave is coming!

2022-06-15 21:47 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            "INSERT INTO GlobalChatChannel VALUES (%s, %s);", (name, channelid)
長い一行だけってのが気持ち悪い。
第二引数を改行して欲しい。

2022-06-15 21:47 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +from rtlib.common.json import dumps
coreの下に置いて欲しい。

2022-06-15 21:47 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        self, name: str, author_id: int, channel_id: int, settings: SettingType
`settings`が複数形なのに`SettingType`がそうじゃないのはなぜ。
複数形じゃないに統一して欲しい。

2022-06-15 21:47 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def check_exists(self, name: str, password: str | None = None) -> bool:
これなんで設定を要求しているの？
設定によっては既に使われている名前でも一つのグローバルチャットって扱いになるの？

2022-06-15 21:47 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            "SELECT * FROM GlobalChat WHERE name = %s;",
`name`が誤字っている。

2022-06-15 21:47 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +
`del _help`でもう使わない参照消して。

2022-06-15 22:48 UTC, tuna2134 commented on cogs/server-tool/globalchat.py
> +    async def check_exists(self, name: str, password: str | None = None) -> bool:
どこかわからない

2022-06-15 23:31 UTC, tasuren commented
もしできたならレビューリクエストをしてね。

2022-06-15 23:35 UTC, tuna2134 commented
@tasuren 頼む

2022-06-16 00:40 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            "INSERT INTO GlobalChatChannel VALUES (%s, %s);", (name, channelid)
これがなおっていない。

2022-06-16 00:41 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def check_exists(self, name: str, password: str | None = None) -> bool:
`password`

2022-06-16 00:44 UTC, tasuren requested changes
The wind is coming!

2022-06-16 00:44 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        for channel_id in await cursor.fetchall():
これだと`(ID,)`が`channel_id`に入るから、`(channel_id,)`って書いて。

2022-06-16 00:44 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +
ヘルプの間にある空の行を消して。

2022-06-16 01:20 UTC, tuna2134 commented
@tasuren fixed

2022-06-16 01:51 UTC, tasuren requested changes
The wind is coming!

以下の二つが放置されている。
https://github.com/RextTeam/rt-bot/pull/138#discussion_r898588528
https://github.com/RextTeam/rt-bot/pull/138#discussion_r898588701

2022-06-16 02:09 UTC, tuna2134 commented on cogs/server-tool/globalchat.py
> +    async def check_exists(self, name: str, password: str | None = None) -> bool:
> password

passwordはjsonでnullにされるから、めんどくさくてそうしているだけ。
パスワードが間違っていたら、404出す

2022-06-16 02:11 UTC, tuna2134 commented
> The wind is coming!
> 
> 以下の二つが放置されている。 [#138 (comment)](https://github.com/RextTeam/rt-bot/pull/138#discussion_r898588528) [#138 (comment)](https://github.com/RextTeam/rt-bot/pull/138#discussion_r898588701)

前者は修正した
後者はコメント見て欲しい

2022-06-16 02:16 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def check_exists(self, name: str, password: str | None = None) -> bool:
つまりこれは接続が可能かどうかをチェックする関数っていうこと？

2022-06-16 02:22 UTC, tuna2134 commented on cogs/server-tool/globalchat.py
> +    async def check_exists(self, name: str, password: str | None = None) -> bool:
そうだね
それもそうだけど、あるかどうか確認するのがメイン
パスワードチェックも一応やってくれる

2022-06-16 03:28 UTC, tuna2134 commented on cogs/server-tool/globalchat.py
> +    async def check_exists(self, name: str, password: str | None = None) -> bool:
ないと思う

2022-06-16 06:58 UTC, yaakiyu commented on cogs/server-tool/globalchat.py
> +    async def check_exists(self, name: str, password: str | None = None) -> bool:
後々グロチャ一覧とか、グロチャの公開設定(一覧に乗せるかどうか)を変えられるようにするときにめんどくさくなるから僕はやめといたほうがいいと思う

2022-06-16 07:02 UTC, tuna2134 commented on cogs/server-tool/globalchat.py
> +    async def check_exists(self, name: str, password: str | None = None) -> bool:
正直いらないと思うのではい

2022-06-16 07:02 UTC, tuna2134 commented on cogs/server-tool/globalchat.py
> +    async def check_exists(self, name: str, password: str | None = None) -> bool:
公開設定もまだ作ってない
一覧も需要があるのか？

2022-06-16 07:16 UTC, tuna2134 commented
> The wind is coming!
> 
> 以下の二つが放置されている。 [#138 (comment)](https://github.com/RextTeam/rt-bot/pull/138#discussion_r898588528) [#138 (comment)](https://github.com/RextTeam/rt-bot/pull/138#discussion_r898588701)

後者も修正した

2022-06-16 07:16 UTC, tuna2134 reviewed
修正した

2022-06-16 22:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def check_exists(self, name: str, password: str | None = None) -> bool:
ある。

2022-06-16 22:32 UTC, tasuren requested changes
The wind is coming!

2022-06-16 22:32 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +from collections.abc import AsyncIterator
これtypingの下にして。

2022-06-16 22:43 UTC, tuna2134 commented
@tasuren 修正した

2022-06-16 23:16 UTC, yaakiyu commented on cogs/server-tool/globalchat.py
> +    async def check_exists(self, name: str, password: str | None = None) -> bool:
僕はめっちゃほしい。
「公式サーバーにあるこのグロチャの名前はなんだ！」
みたいな。
人気のグロチャとか入ってみたいじゃん()

2022-06-17 07:22 UTC, tasuren requested changes
The wind is coming.

2022-06-17 07:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        if not await self.data.check_exists(name):
こういうチェックさ、`connect`関数内でやってよ。
返信は`Cog.BadRequest`に返信内容の文字列または辞書渡してエラー発生させればいい。

2022-06-17 07:22 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        name = await self.data.get_name(message.channel.id)
この変数一度しか使わないかr(ry

2022-06-18 12:09 UTC, tuna2134 commented on cogs/server-tool/globalchat.py
> +        if not await self.data.check_exists(name):
ok

2022-06-18 12:12 UTC, tuna2134 commented on cogs/server-tool/globalchat.py
> +        name = await self.data.get_name(message.channel.id)
修正した

2022-06-18 20:27 UTC, tuna2134 commented
@tasuren fin

2022-06-18 23:50 UTC, tasuren requested changes
The wind is coming!

2022-06-18 23:50 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                            io.BytesIO(await resp.read()),
`discord.Attachment.to_file`使って。

2022-06-18 23:50 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        if not await self.data.is_connected(message.channel.id):
ここらへんのDataManagerへのアクセスを新しく接続とcursorを作ってそのcursorだけで完結させて。

2022-06-18 23:50 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        description="The command of globalchat.", aliases=("gc", "gchat"),
やっぱ`aliases`を改行して`fsparent`の改行を消して。

2022-06-18 23:50 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        aliases=("join", "参加")
`c`と`さか`のエイリアス追加して。

2022-06-18 23:50 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def connect(self, ctx, name: str, password: str | None = None):
`password`の左に`*`を入れて。

2022-06-18 23:50 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                en="Created", ja="作成しました。"
これくらいなら一行にまとめて。

2022-06-18 23:50 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        if await self.data.is_connected(ctx.channel.id):
この接続確認を`create_chat`で行って。
`Cog.BadRequest`に辞書か文字列で返信内容渡してエラー発生させれば返信できるからそうして。

2022-06-18 23:50 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def check_exists(self, name: str) -> bool:
`is_existed`にして。

2022-06-18 23:50 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            setting = loads(row[0])
これ変数を作る必要がない。

2022-06-24 11:26 UTC, tuna2134 commented
@tasuren fixed

2022-06-24 22:52 UTC, tasuren requested changes
An Apple Disaster!!

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            (name)
`,`がない。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            "SELECT * FROM GlobalChat WHERE Name = %s;",
`LIMIT 1`って最後に置いて一つまでしか取得しないようにして。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            "SELECT Setting FROM GlobalChat WHERE Name = %s;",
`LIMIT 1`を最後に置いて一つまでしか探さないようにして。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                await self.disconnect(channel_id, cursor=cursor)
不明なチャンネルの削除は`clean`関数でやってほしい。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        self, name: str
これ改行しないで。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            if len(message.attachments) > 0:
数え上げるのやめて`message.attachments`にして。
そっちの方が全て数え上げないから効率が良い。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            files = []
リスト内包表記を使って`send`に直接入れて。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            await webhook.send(
`rtutil.utils.webhook_send`を使って。
そしたら、ウェブフックもなければ自動で作成される。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        if not await self.data.is_connected(message.channel.id):
これが治っていない。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        if not await self.data.check_exists(name):
これはどうなったの？

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        if await self.data.is_connected(ctx.channel.id):
この接続確認を`create_chat`で行って。
`Cog.BadRequest`に辞書か文字列で返信内容渡してエラー発生させれば返信できるからそうして。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            name, ctx.author.id, ctx.channel.id, {"password": password}
`{...}`の部分を改行して。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            "INSERT INTO GlobalChatMessage VALUES(%s, %s, %s);",
`VALUES`の後空白を入れてほしい。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            return False
`return`するんじゃなくて`Cog.BadRequest`使って返信して欲しい。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            raise Cog.BadRequest("You are already connected to globalchat.")
辞書で多言語対応できるから辞書で渡して。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        if await self.data.is_connected(ctx.channel.id):
`create_chat`でこのチェックは済ませている。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def create_chat(
名前を`create`にして欲しい。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            raise Cog.BadRequest("You are already connected to this globalchat.")
`rtlib.t`関数が内部で使用されるから辞書形式で渡してほしい。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +# RT - server-tool global
`server-tool`いらない。`Global Chat`にして。

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +class SettingType(TypedDict):
名前を`Setting`にして欲しい。
あと、`total=False`って入れて欲しい。
(これはキーが必ずあるわけではないということを示すためのもの。)

2022-06-24 22:52 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def connect(self, name: str, channelid: int) -> None:
`channelid`を`channel_id`にして。

2022-06-25 10:24 UTC, tuna2134 commented
@tasuren fin

2022-06-25 23:16 UTC, tuna2134 commented
@tasuren チェックして

2022-06-25 23:31 UTC, tasuren requested changes
An Apple Disaster!!

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                "ja": "すでにこのグローバルチャットに接続しています。"
> すでに

を漢字にして欲しい。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            "SELECT * FROM GlobalChatChannel WHERE ChannelId = %s;",
`LIMIT 1`って最後に置いて一つまでしか取得しないようにして。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        self, name: str, password: str | None
これ改行しないで。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                await self.disconnect(channel_id, cursor=cursor)
チャンネルが見つからない時の削除は`clean`関数でのみにして欲しい。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +
いらないデータを消す`clean`関数を実装して。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    @globalchat.command(
これの引数改行する必要がなさそうだ。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    @discord.app_commands.describe(name="Global chat name")
`password`引数の説明がない。
後説明は`.`で終わるようにちゃんとした文にして欲しい。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        if not await self.data.check_exists(name):
これが治っていない。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        aliases=("remove", "rm", "退出")
グローバルチャットの接続が`connect`だからこれは`disconnect`にして欲しい。
`leave`はエイリアスに追加してほしい。
あと、日本語の一文字のエイリアス`た`とか追加して。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +             .merge_description("headline", ja="グローバルチャット関連です。"))
インデントしすぎ。
上の行のインデントに一つインデント追加した感じにして。
下にある他のもそう。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        if isinstance(message.author, discord.User):
上の`if`にまとめて。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +        async with self.bot.pool.acquire() as connection:
これの上に空の行を入れて。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +            async with connection.cursor() as cur:
`cur`って省略しないで。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                    name, cursor=cur
これ改行しなかったら何文字になる？

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                name = await self.data.get_name(message.channel.id, cursor=cur)
これ上の`if`にまとめて。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                async for channel in self.data.get_all_channel(
これの上に空の行を作ってほしい。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                        message.clean_content,
これ改行しなかったら何文字になる？

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                        continue
下にあるコードが関数実行一つだけだから、`continue`しないで`if`の中で`send`するようにして。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +                Name TEXT, AuthorId BIGINT, Setting JSON
`typing.NamedTuple`で`Data`っていうやつ作って。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +
上のコメントに書いた`Data`を返す`fetch_global_chat`っていう関数を作って。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def check_password(
`name`引数を`data`にして上のコメントで書いた`Data`を受け取るようにして。
その`Data`のパスワードから確認するようにして。

2022-06-25 23:31 UTC, tasuren commented on cogs/server-tool/globalchat.py
> +    async def get_all_channel(self, name: str, **_) -> AsyncIterator[discord.TextChannel]:
名前を`get_channels`にして。

2022-06-26 01:35 UTC, tasuren requested changes
まだ全て治っていない。

2022-06-28 08:21 UTC, tuna2134 commented
@tasuren 直した

2022-06-29 02:36 UTC, tuna2134 commented
@tasuren fin

2022-06-29 04:27 UTC, tasuren commented
ブランチを`tasuren`にしてくれない？

2022-06-29 05:04 UTC, tasuren approved these changes
後は僕がやる。

2022-06-29 05:04 UTC, merged