new: gban(作成途中)
RextTeam/rt-bot pull request #146
Opened 2022-06-16 03:14 UTC by yaakiyu

# Pull Request

## チェックリスト

- [x] 新規機能追加

## 詳細

GBAN機能。

2022-06-16 13:04 UTC, yaakiyu commented
完成。

2022-06-16 22:29 UTC, tasuren requested changes
The wave is coming!

2022-06-16 22:29 UTC, tasuren commented on cogs/rt/admin.py
> +    async def mod_gban(self, ctx, mode: Literal["add", "remove"], user_id: int):
`mod_`いらない。

2022-06-16 22:29 UTC, tasuren commented on cogs/rt/admin.py
> +        result = await getattr(self.bot.cogs["GBan"].data, f"{mode}_user")(user_id)
この変数一度しか使わないから変数を作る必要がない。

2022-06-16 22:29 UTC, tasuren commented on cogs/rt/gban.py
> +
「GBANのコグです」ってコメント入れて。

2022-06-16 22:29 UTC, tasuren commented on cogs/rt/gban.py
> +            """CREATE TABLE IF NOT EXISTS GBanSetting (
`GlobalBan`っていうテーブル名を使っているのなら、こっちもりゃくさないで`GlobalBanSetting`って感じにして。
あと、これサーバーIDだけでいいんじゃない？
サーバーIDが保存されてるかどうかでチェックってこと。

2022-06-16 22:29 UTC, tasuren commented on cogs/rt/gban.py
> +        async for rows in self.fetchstep(cursor, "SELECT UserId FROM GlobalBan;"):
これ`rows`じゃなくて`row`にして。
そして`yield row[0]`ってやって。

2022-06-16 22:29 UTC, tasuren commented on cogs/rt/gban.py
> +        else:
このelseいらない。

2022-06-16 22:29 UTC, tasuren commented on cogs/rt/gban.py
> +        else:
このelseいらない。

2022-06-16 22:29 UTC, tasuren commented on cogs/rt/gban.py
> +            )"""
セミコロンを付けて。

2022-06-16 22:29 UTC, tasuren commented on cogs/rt/gban.py
> +    async def check(self, ctx, user: discord.User | discord.Object):
`user`引数の左に`*`をおいて。

2022-06-16 22:29 UTC, tasuren commented on cogs/rt/gban.py
> +    @commands.command(description="Check if user is Gbanned")
GBANコマンドをグループコマンドにして、checkをサブコマンドにして。

2022-06-16 22:29 UTC, tasuren commented on cogs/rt/gban.py
> +
ここの空白いらない。

2022-06-16 22:29 UTC, tasuren commented on cogs/rt/gban.py
> +async def setup(bot: RT):
`-> None`を入れて。

2022-06-16 22:30 UTC, tasuren commented
そういえば`Cog.BadRequest`でエラー発生させれば、そのエラーに渡した辞書か文字列が返信されるよ。

2022-06-16 23:21 UTC, yaakiyu commented on cogs/rt/gban.py
> +            """CREATE TABLE IF NOT EXISTS GBanSetting (
なるほど

2022-06-17 00:18 UTC, yaakiyu commented
修正。

2022-06-23 05:20 UTC, yaakiyu commented
@tasuren 確認求む。

2022-06-23 06:51 UTC, tasuren requested changes
An Apple Disaster!!

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/gban.py
> +        if not await cursor.fetchone():
`not`消して`else`の中身と入れ替えて。

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/gban.py
> +                """INSERT INTO GlobalBanSetting VALUES (%s)""",
`"""`不要なのと、`;`が最後にない。
これについて全部のSQLで確認をして。

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/gban.py
> +    async def toggle_gban(self, guild_id) -> bool:
`-> bool:`とあるが、何も返却されていない。

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/gban.py
> +
この行を消して。

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/gban.py
> +        await ctx.typing()
`toggle`っていうコマンド作ってそこにこれを実装して。
これだとスラッシュで使えない。

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/admin.py
> +            for g in self.bot.guilds:
`g`じゃなくて`guild`にして。

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/gban.py
> +            en=f"The user is {'not ' if not result else ''}found in Gban users."
`not`やめて`if`の値入れ替えて。

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/gban.py
> +
`on_member_join`でメンバーが参加した際にGBANされているかを確認して。

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/gban.py
> +            yield row
`row[0]`にして。

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/gban.py
> +    async def get_all_guilds(self) -> AsyncIterator[tuple[int]]:
`get_avaliable_guild_ids`にして。
あと下に書いたコメントを修正したら返り値のイテレータの中身の型を`tuple[int]`から`int`にして。

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/gban.py
> +        # GBanのオンオフ切り替え用のデータベースを作成する。
これいらない。

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/admin.py
> +                        reason="RTグローバルBANのため。"
一行にして。
それと、`core.t`で理由を多言語対応させて。

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/admin.py
> +            ignores = list(await self.bot.cogs["GBan"].data.get_all_guilds())
これ`ignores`じゃなくて`avaliable_guild_ids`じゃない？
無視じゃなくて有効なギルド。
あと、`list`じゃなくて`set`使って。そっちの方が速いことがある。

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/admin.py
> +                    pass
`...`にして。

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/admin.py
> +                    await g.ban(discord.Object(id=user_id),
`id=`いらない。

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/admin.py
> +        await ctx.typing()
これやめて編集方式にしてほしい。
GBAN後に更新するって感じ。

2022-06-23 06:51 UTC, tasuren commented on cogs/rt/gban.py
> +            user_or_guild = "User" if table == "GlobalBan" else "Guild"
`for`で指定してるタプルを二次元タプルにしてそこに入れて。
あと`user_or_guild`じゃなくて`column`にして。

2022-06-23 23:16 UTC, yaakiyu commented on cogs/rt/gban.py
> +        )))
pyright使いたいけど
僕の開発環境(学校のiPadのsafariでgithubのリポジトリを開き`.`をおす)だとpyrightの拡張機能が入らない...

2022-06-23 23:27 UTC, yaakiyu commented on cogs/rt/gban.py
> +    async def get_all_guilds(self) -> AsyncIterator[tuple[int]]:
GlobalBanSettingは設定を無効化したサーバーだけ登録するようにするつもり。
なのでavailableではなくunabailableにしたい。

2022-06-24 00:41 UTC, tasuren commented on cogs/rt/gban.py
> +        )))
codespacesだっけ。それ使ってる？

2022-06-24 00:44 UTC, tasuren commented on cogs/rt/gban.py
> +    async def get_all_guilds(self) -> AsyncIterator[tuple[int]]:
じゃあそうして。

2022-06-24 03:00 UTC, yaakiyu commented on cogs/rt/gban.py
> +        )))
使ってる

2022-06-24 03:01 UTC, yaakiyu commented on cogs/rt/gban.py
> +    async def get_all_guilds(self) -> AsyncIterator[tuple[int]]:
とは言ったもののcleanの処理のために上の関数と表記を整えたい(じゃないとforで回しにくい)のでどうしよう

2022-06-24 03:03 UTC, yaakiyu commented
一応ほぼ修正完了。

2022-06-24 03:25 UTC, yaakiyu commented on cogs/rt/gban.py
> +        )))
...と、思っていただけだったっぽい。
今使う方法を知って使ってみたらpylanceが入った。

2022-06-24 05:11 UTC, yaakiyu commented
修正した。
他のPRも全てpyrightでチェック済みなので確認してほしい。
@tasuren

2022-06-24 23:03 UTC, tasuren requested changes
The wave is coming!

2022-06-24 23:03 UTC, tasuren commented on cogs/rt/gban.py
> +        if await self.data.is_guild_exists(member.guild.id):
ここのチェックをまとめて行う関数`check`を`DataManager`に実装して。

2022-06-24 23:03 UTC, tasuren commented on cogs/rt/gban.py
> +                UserId BIGINT PRYMARY KEY NOT NULL
理由は記録しないの？

2022-06-24 23:03 UTC, tasuren commented on cogs/rt/admin.py
> +                    guild, error, await self.bot.search_user(user_id)
この`search_user`を`for`の前で実行して。
じゃないとBANする度にAPIリクエストする羽目になる可能性がある。

2022-06-27 01:42 UTC, tasuren requested changes
The wind is coming.

2022-06-27 01:42 UTC, tasuren commented on cogs/rt/admin.py
> +        await message.edit(content="".join(("Ok: ", 'succeeded'
ここ一行にしたら何文字になる？

2022-06-27 01:42 UTC, tasuren commented on cogs/rt/gban.py
> +        "ユーザーがそのサーバーでBANされるべきかを調べます。"
「その」を「指定された」にして欲しい。

2022-06-27 01:42 UTC, tasuren commented on cogs/rt/gban.py
> +        if await self.data.check(member.id, member.guild.id):
チェックで理由も取得してほしい。
じゃないと二回同じ場所にあるデータを探すことになる。

2022-06-28 03:47 UTC, yaakiyu commented on cogs/rt/admin.py
> +        await message.edit(content="".join(("Ok: ", 'succeeded'
100文字まで行かなかったわ

2022-06-28 04:08 UTC, yaakiyu commented
修正。
@tasuren

2022-06-28 07:31 UTC, tasuren requested changes
The wind is coming.

2022-06-28 07:31 UTC, tasuren commented on cogs/rt/admin.py
> +                            ja="RTグローバルBAN \n理由:{reason}",
インデント一つ多い。

2022-06-28 07:31 UTC, tasuren commented on cogs/rt/gban.py
> +    async def is_user_exists(self, user_id: int, **_) -> tuple[int, str]:
これデータ取得するだけだから`is_user_exists`の名前は間違いとなる。
ちゃんとした名前にして。
あと、返り値が`None`の可能性があるが、その型が指定されていない。
それと、ユーザーIDはこの関数の実行に必要なもので既にわかっている。
だから、この関数はタプルでユーザーIDを渡す必要はない。

2022-06-29 02:17 UTC, yaakiyu commented on cogs/rt/gban.py
> +    async def is_user_exists(self, user_id: int, **_) -> tuple[int, str]:
それならこの関数get_reasonでええやんって思った
統合しよ

2022-06-29 04:27 UTC, tasuren commented
ブランチを`tasuren`にしてくれない？

2022-06-29 05:02 UTC, tasuren commented
自分で変えれたわ。

2022-06-29 05:03 UTC, tasuren approved these changes
後は僕がやる。

2022-06-29 05:03 UTC, merged