change:getで警告を出す()
RextTeam/rt-bot pull request #163
Opened 2022-07-02 10:49 UTC by ysmreg

# Pull Request

## チェックリスト

- [ ] 新規機能追加
- [ ] バグ修正

## 詳細

getの関数使用時に警告を出す

2022-07-02 10:50 UTC, ysmreg commented
@tasuren レビューをリクエスト出来ないです

2022-07-02 10:51 UTC, tasuren commented
それならこれからはメンションで知らせてください。
ではレビューします。

2022-07-02 10:51 UTC, ysmreg commented
わかりました

2022-07-02 10:53 UTC, tasuren requested changes
エラーを発生させるのではなく、標準ライブラリの`warnings`を使って欲しい。
それと、`get_`から始まる名前の関数を、自動で警告を出す関数に置き換えるようにしてほしい。
これは継承ではなく、クラス定義後に行う。名前は`RT.__dict__.keys()`で取り出せばいい。

2022-07-02 11:48 UTC, ysmreg commented
@tasuren 変更完了した

2022-07-02 11:56 UTC, yaakiyu reviewed
気になったことがあったので。

2022-07-02 11:56 UTC, yaakiyu commented on core/bot.py
> +            raise SyntaxError("This function is not available. Use a function that starts with search_ instead")
SyntaxErrorいらない。もしエラー送出するとしてもNotImplementedかな
あとおそらくnot availableではない...?

2022-07-02 11:56 UTC, yaakiyu commented on core/bot.py
> +            if "get" in func:
startswithで判定すべき。

2022-07-02 11:56 UTC, yaakiyu commented on core/bot.py
> +                exec("self." + func + " = self.decolator_for_get(self." + func + ")")
getattrとsetattr使ったほうがいいよ。

2022-07-02 11:58 UTC, ysmreg commented
なるほど

2022-07-02 12:04 UTC, ysmreg commented
変更完了

2022-07-02 12:07 UTC, ysmreg commented on core/bot.py
> +            raise SyntaxError("This function is not available. Use a function that starts with search_ instead")
NotImplementErrorに変更した

2022-07-02 12:07 UTC, ysmreg commented on core/bot.py
> +            if "get" in func:
変更完了

2022-07-02 12:08 UTC, ysmreg commented on core/bot.py
> +                exec("self." + func + " = self.decolator_for_get(self." + func + ")")
変更完了しました

2022-07-02 12:11 UTC, tasuren requested changes
The wind is coming.

2022-07-02 12:11 UTC, tasuren commented on core/bot.py
> +
この空の行を消して欲しい。

2022-07-02 12:11 UTC, tasuren commented on core/bot.py
> +            raise NotImplementedError("This function is not available. Use a function that starts with search_ instead")
`super`使って親クラスの`get_...`呼び出すようにして欲しい。

2022-07-02 12:11 UTC, tasuren commented on core/bot.py
> +        for func in dir(self):
定義後にやって欲しい。
あと、`dir`は名前を取り出すだけで、関数は取り出さない。

2022-07-02 12:15 UTC, ysmreg commented
わかりました

2022-07-02 12:18 UTC, ysmreg commented on core/bot.py
> +        for func in dir(self):
定義後に変更する。さっきjskでbot.__dict__みて関数入ってなかったけど大丈夫かなって思った？

2022-07-02 12:31 UTC, ysmreg commented
変更完了しました
@tasuren

2022-07-02 22:32 UTC, tasuren commented on core/bot.py
> +            raise NotImplementedError("This function is not available. Use a function that starts with search_ instead")
これがなおっていない。

2022-07-02 22:34 UTC, tasuren requested changes
The wind is coming.

2022-07-02 22:34 UTC, tasuren commented on core/bot.py
> +        for func in dir(self):
`dir`は値ではなく名前を返す。
だからこれではだめ。
それと、インスタンス後ではなくてクラス定義後にこれやってほしい。

2022-07-02 22:34 UTC, tasuren commented on core/bot.py
> +            raise NotImplementedError("This function is not available. Use a function that starts with search_ instead")
これがなおっていない。

2022-07-02 23:10 UTC, yaakiyu commented on core/bot.py
> +        for func in dir(self):
おそらく__dict__属性には関数は含まれないけど大丈夫なの？
@tasuren

2022-07-02 23:22 UTC, tasuren commented on core/bot.py
> +        for func in dir(self):
含まれてるよ。
`__dict__`は属性の値を格納してるとこだから。
今実験して確かめもした。↓
![image](https://user-images.githubusercontent.com/45121209/177018768-5330316b-f26c-442d-ae4e-61d456a5a999.jpeg)

2022-07-02 23:44 UTC, yaakiyu commented on core/bot.py
> +        for func in dir(self):
https://qiita.com/kazetof/items/751be29f208836cf9bf4#__dict__
hmm
あ、これってインスタンス化前と後で変わるんかな

2022-07-02 23:46 UTC, tasuren commented on core/bot.py
> +        for func in dir(self):
僕はインスタンス化する前にやってほしいって言った。
レビューで

2022-07-03 00:02 UTC, ysmreg commented
@tasuren 修正完了

2022-07-03 00:06 UTC, tasuren requested changes
The wind is coming.

2022-07-03 00:06 UTC, tasuren commented on core/bot.py
> +
この空白を消してほしい。

2022-07-03 00:06 UTC, tasuren commented on core/bot.py
> +            raise NotImplementedError("This function is not available. Use a function that starts with search_ instead")
`super`使って親クラスの`get_...`呼び出すようにして欲しい。

2022-07-03 00:06 UTC, tasuren commented on core/bot.py
> +    def decolator_for_get(func):
インデントを下げてほしい。
これだとクラスのメソッドになってしまう。
それと、名前を`mark_get_as_deprecated`(getを非推奨としてマークする)にしてほしい。

2022-07-03 00:06 UTC, tasuren commented on core/bot.py
> +        setattr(RT, func, RT.decolator_for_get(RT.__dict__[func]))
`self.`を`RT`にして。
じゃないと`self`は何ってなって動かない。

2022-07-03 00:16 UTC, ysmreg commented
@tasuren 修正完了

2022-07-03 00:29 UTC, tasuren requested changes
The wind is coming!

2022-07-03 00:29 UTC, tasuren commented on core/bot.py
> +        raise NotImplementedError("This function is not available. Use a function that starts with search_ instead")
エラーを起こさないで。

2022-07-03 00:29 UTC, tasuren commented on core/bot.py
> +for func in RT.__dict__.keys():
`func`を`name`にして。

2022-07-03 00:29 UTC, tasuren commented on core/bot.py
ここにもう一個空の行を入れて欲しい。

2022-07-03 00:29 UTC, tasuren commented on core/bot.py
> +        getattr(super, func.__name__)(*args, **kwargs) # 元のメゾットを実行
思ったけどこれ`super`使う必要なかった。
やっぱ`func(*args, **kwargs)`にして。

2022-07-03 00:29 UTC, tasuren commented on core/bot.py
> +        warnings.warn("This function is not available. Use a function that starts with search_ instead")
> `with seatch_ instead`

の部分のsearch_を\`search_...\`にして欲しい。
あと、最後にピリオドを付けて。

2022-07-03 00:29 UTC, tasuren commented on core/bot.py
> +    def wrapper(*args, **kwargs):
標準ライブラリのfunctoolsの`wraps`デコレータをこれに付けて欲しい。
`@wraps(func)`

2022-07-03 00:53 UTC, ysmreg commented
@tasuren 修正完了

2022-07-03 01:11 UTC, tasuren requested changes
The wind is coming.

2022-07-03 01:11 UTC, tasuren commented on core/bot.py
> +
ここにもう一個空の行を入れて欲しい。

2022-07-03 01:11 UTC, tasuren commented on core/bot.py
> +        func(*args, **kwargs) # 元のメゾットを実行
`return`を置いて欲しいのとコメントを消して欲しい。

2022-07-03 01:11 UTC, tasuren commented on core/bot.py
> +
こことここの下の空の行を消して欲しい。

2022-07-03 01:16 UTC, ysmreg commented
@tasuren 修正完了

2022-07-03 01:41 UTC, tasuren commented on core/bot.py
> +
これがなおっていない。
行がひとつしか消されていない。

2022-07-03 01:41 UTC, tasuren commented on core/bot.py
> +
これがなおっていない。
行がひとつしか消されていない。

2022-07-03 01:45 UTC, tasuren requested changes
The wind is coming.

2022-07-03 01:45 UTC, tasuren commented on core/bot.py
> +
この行を消して欲しい。

2022-07-03 01:45 UTC, tasuren commented on core/bot.py
> +        warnings.warn("This function is not available. Use a function that starts with search_... instead.")
最初の一文を"This function is deprecated."にして欲しい。
それと、`if not kwargs.pop("force", False):`を置いて、その中にこの警告を出すやつを置いて欲しい。

2022-07-03 01:55 UTC, ysmreg commented
@tasuren 修正完了

2022-07-03 01:59 UTC, tasuren requested changes
The wind is coming.

2022-07-03 01:59 UTC, tasuren commented on core/bot.py
> +            return func(*args, **kwargs)
これインデント一つ下げて。

2022-07-03 01:59 UTC, tasuren commented on core/bot.py
> +import warnings
`from os import ...`の下にして欲しいのと、`from warnings import warn`で使うやつだけimportして。

2022-07-03 03:34 UTC, ysmreg commented
@tasuren 修正完了

2022-07-03 03:36 UTC, tasuren commented
一応聞く
動作確認はした？

2022-07-03 03:37 UTC, ysmreg commented
動作確認はしてないです

2022-07-03 03:38 UTC, ysmreg commented
()

2022-07-03 03:40 UTC, tasuren commented
パソコンは今使える状態？

2022-07-03 03:41 UTC, ysmreg commented
パソコンは使えます

2022-07-03 03:46 UTC, ysmreg commented
@tasuren

2022-07-03 03:57 UTC, ysmreg commented
database関連のところでエラーでて起動出来なかったです

2022-07-03 04:03 UTC, yaakiyu commented
`bash build.sh`やって
mysqlを用意して
secret.jsonに記入するのだ

2022-07-03 04:05 UTC, ysmreg commented
わかりました。やってみます

2022-07-03 04:06 UTC, ysmreg commented
起動出来ました

2022-07-03 04:16 UTC, tasuren commented
じゃあ動作は確認できた？

2022-07-03 06:17 UTC, ysmreg commented
起動だけ、出来た。関数の実行は出来ないです
@tasuren

2022-07-03 06:20 UTC, ysmreg commented
![Screenshot_20220703-124128_Discord.jpg](https://user-images.githubusercontent.com/33682244/177027609-68622bd2-bb1b-4496-bb90-6a3160de08b3.jpg)

2022-07-03 06:33 UTC, yaakiyu commented
Not Ownerよね
テストできないのが辛い()

2022-07-03 06:36 UTC, ysmreg commented
Not Ownerだね。テスト出来ないから辛いね

2022-07-03 06:38 UTC, tuna2134 commented
Owner追加は反対します(おい

2022-07-03 06:39 UTC, ysmreg commented
> Owner追加は反対します(おい

反対でもいいよ。その代わり関数とか管理者専用のコマンドは動作確認してほしい

2022-07-03 06:41 UTC, tuna2134 commented
まあ所有者もオーナー扱いするようにさっきPR出した

2022-07-03 06:46 UTC, ysmreg commented
wow

2022-07-03 07:34 UTC, tasuren commented
そのPRマージした。
@ysmreg だからテストして欲しい。

2022-07-03 09:07 UTC, ysmreg commented
わかりました。今パソコンが手元にないので後でテストしておきます

2022-07-03 10:23 UTC, ysmreg commented
RTの__dict__にもcommands.Botの__dict__にもget_userが無いのはなんでだろう

2022-07-03 10:24 UTC, tuna2134 commented
inspect使えば？

2022-07-03 10:26 UTC, yaakiyu commented
インスタンス化前に調べればあると思う

2022-07-03 10:28 UTC, ysmreg commented
> インスタンス化前に調べればあると思う

commands.BotにもRTにもないけどClientにはあるみたいなんだよね

2022-07-03 10:31 UTC, ysmreg commented
![Screenshot_20220703-193001_Discord.jpg](https://user-images.githubusercontent.com/33682244/177035623-e0b42f81-a640-453a-845f-74c774f17a79.jpg)
そしてRTの大元はdiscord.client.Clientだと判明した

2022-07-03 10:47 UTC, ysmreg commented
inspect使ったら出来そうだね

2022-07-03 10:55 UTC, ysmreg commented
inspectはインスタンス化後じゃないと使えなかった

2022-07-03 11:16 UTC, ysmreg commented
どうすれば完成するのかわからない状態

2022-07-03 11:24 UTC, tasuren commented
今の状態で完成してるんじゃないの？
一見すると動きそう。

2022-07-03 12:48 UTC, ysmreg commented
後でテストしてみる

2022-07-03 12:59 UTC, ysmreg commented
@tasuren 動作確認出来ました

2022-07-03 13:09 UTC, tasuren requested changes
Last wave!

2022-07-03 13:09 UTC, tasuren commented on core/bot.py
> +def mark_get_as_deprecated(func):
名前の最初に`_`を付けて欲しい。

2022-07-03 13:13 UTC, ysmreg commented
@tasuren 修正完了しました

2022-07-03 13:34 UTC, tasuren approved these changes
Nice job!

2022-07-03 13:34 UTC, merged