fix: stacklevelを変更した
RextTeam/rt-bot pull request #169
Opened 2022-07-05 06:58 UTC by ysmreg

# Pull Request

## チェックリスト

- [ ] 新規機能追加
- [ ] バグ修正

## 詳細

stacklevelを変更しただけです

2022-07-05 07:28 UTC, tasuren commented
ちゃんと警告発生箇所表示されるようになった？

2022-07-05 07:33 UTC, ysmreg commented
大丈夫、呼び出し元がわかるようになった

2022-07-05 07:35 UTC, tasuren requested changes
The wind is coming.

2022-07-05 07:35 UTC, tasuren commented on core/bot.py
> +            warn("This function is deprecated. Use a function that starts with search_... instead.",stacklevel=2)
引数と引数の間に空白を入れて。

2022-07-08 09:54 UTC, tasuren commented
@ysmreg これできれば早くやってほしい。

2022-07-08 10:04 UTC, tasuren commented
それと、モンキーパッチで`discord.Guild`の`get_member`にも非推奨を適用してくれない？

2022-07-08 11:32 UTC, ysmreg commented
@tasuren 遅くなったけど修正完了した。モンキーパッチはやった事ないから時間かかるかもしれない

2022-07-08 13:20 UTC, ysmreg commented
やってみる

2022-07-17 04:06 UTC, closed without merging